// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OL.Infrastructure;

#nullable disable

namespace OL.Migrator.Migrations
{
    [DbContext(typeof(OLDbContext))]
    [Migration("20230914134837_14-09-2023_init")]
    partial class _14092023_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ol")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OL.Domain.Entities.OLCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OLCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("ParrentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OLCategoryId");

                    b.ToTable("ol_categories", "ol");
                });

            modelBuilder.Entity("OL.Domain.Primitives.Entities.OLTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("OLCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OLCategoryId");

                    b.ToTable("ol_translations", "ol");
                });

            modelBuilder.Entity("OL.Domain.Entities.OLCategory", b =>
                {
                    b.HasOne("OL.Domain.Entities.OLCategory", null)
                        .WithMany("Childs")
                        .HasForeignKey("OLCategoryId");
                });

            modelBuilder.Entity("OL.Domain.Primitives.Entities.OLTranslation", b =>
                {
                    b.HasOne("OL.Domain.Entities.OLCategory", null)
                        .WithMany("Translations")
                        .HasForeignKey("OLCategoryId");
                });

            modelBuilder.Entity("OL.Domain.Entities.OLCategory", b =>
                {
                    b.Navigation("Childs");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
