// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OL.Infrastructure;

#nullable disable

namespace OL.Migrator.Migrations
{
    [DbContext(typeof(OLDbContext))]
    [Migration("20240109061317_add_ol_product_price_history")]
    partial class add_ol_product_price_history
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ol")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OL.Domain.Entities.OLCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ParrentId")
                        .HasColumnType("bigint");

                    b.Property<long>("SystemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ol_categories", "ol");
                });

            modelBuilder.Entity("OL.Domain.Entities.OLProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InstalmentMaxMouth")
                        .HasColumnType("int");

                    b.Property<decimal>("InstalmentMonthlyRepayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("SystemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ol_product", "ol");
                });

            modelBuilder.Entity("OL.Domain.Entities.OLProductPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OLProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OLProductId");

                    b.ToTable("ol_product_price_history", "ol");
                });

            modelBuilder.Entity("OL.Domain.Primitives.Entities.OLTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OLCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OLProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OLCategoryId");

                    b.HasIndex("OLProductId");

                    b.ToTable("ol_translations", "ol");
                });

            modelBuilder.Entity("OL.Domain.Entities.OLProductPriceHistory", b =>
                {
                    b.HasOne("OL.Domain.Entities.OLProduct", null)
                        .WithMany("Price")
                        .HasForeignKey("OLProductId");
                });

            modelBuilder.Entity("OL.Domain.Primitives.Entities.OLTranslation", b =>
                {
                    b.HasOne("OL.Domain.Entities.OLCategory", null)
                        .WithMany("Translations")
                        .HasForeignKey("OLCategoryId");

                    b.HasOne("OL.Domain.Entities.OLProduct", null)
                        .WithMany("Translations")
                        .HasForeignKey("OLProductId");
                });

            modelBuilder.Entity("OL.Domain.Entities.OLCategory", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("OL.Domain.Entities.OLProduct", b =>
                {
                    b.Navigation("Price");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
