name: .NET and Angular CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    # Backend Operations
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'

    - name: Restore dependencies
      run: dotnet restore src/E-Analytics.sln

    - name: Build solution
      run: dotnet build src/E-Analytics.sln --no-restore

    - name: Run Backend Tests
      run: dotnet test src/E-Analytics.sln --no-build --verbosity normal

    # Frontend Operations
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install npm packages
      run: npm install
      working-directory: src/UI/E-Analytics.UI

    - name: Build Angular project
      run: npm run build
      working-directory: src/UI/E-Analytics.UI

    - name: Run Angular tests
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      working-directory: src/UI/E-Analytics.UI
